# Generated by Django 2.2.28 on 2022-11-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressacvbjyxfbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressacvbjyxfbn',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
